export const TOGGLE_TAG = "TOGGLE_TAG"
export const SEARCH = "SEARCH"
export const FETCHING = "FETCHING"
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS"
export const UPDATE_POST_FILTER = "update entire filter, pieced together earlier"
export const UPDATE_CLASS_ID = " restricting filter to particular class"
