export const TOGGLE_TAG = "TOGGLE_TAG"
export const SEARCH = "SEARCH"
export const FETCHING = "FETCHING"
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS"
export const UPDATE_POST_FILTER = "update entire filter, pieced together earlier"
export const UPDATE_CLASS_ID = " restricting filter to particular class"
export const LOADING_SCROLL = "loading next infinite scroll page"
export const APPEND_SEARCH_RESULTS = "appending these next few posts";
export const SET_REACT_POST_DETAILS = "this is the post details for the react client, share l8r."
export const SELECT_DESELECT_POST = "select or deselect post to be opened in details";
export const CLEAR_SELECTED_POST_LIST = "clear the list which contains posts to be viewed in detailed View";